#!/bin/sh
# Copyright 2026 Metatable Inc.
# SPDX-License-Identifier: Apache-2.0

: "${E2E_PROFILE_DESCRIPTION:=Production-readiness certification target for the Docker e2e harness with a mixed fast-api, slow-start, and dependency-sensitive workload matrix}"
: "${E2E_AUTOMATION_SMOKE_JOB:=e2e-smoke}"
: "${E2E_AUTOMATION_CERTIFICATION_JOB:=e2e-certification}"
: "${E2E_AUTOMATION_JOB_NAME:=e2e-certification}"

: "${E2E_TARGET_NOMAD_SERVERS:=3}"
: "${E2E_TARGET_NOMAD_CLIENTS:=3}"
: "${E2E_TARGET_CONSUL_SERVERS:=3}"
: "${E2E_TARGET_TRAEFIK_REPLICAS:=2}"
: "${E2E_TARGET_REDIS_NODES:=1}"
: "${E2E_TARGET_IDLE_SCALER_PLACEMENT:=nomad-system-job}"
: "${E2E_TARGET_IDLE_SCALER_ISOLATION_MODE:=disabled}"

: "${E2E_WORKLOAD_MIX_LABELS:=fast-api,slow-start,dependency-sensitive}"
: "${E2E_WORKLOAD_FAST_API_COUNT:=3}"
: "${E2E_WORKLOAD_SLOW_START_COUNT:=3}"
: "${E2E_WORKLOAD_DEPENDENCY_SENSITIVE_COUNT:=3}"

: "${E2E_JOB_COUNT:=9}"
: "${E2E_NOMAD_CLIENTS:=3}"
: "${E2E_IDLE_TIMEOUT:=10s}"
: "${E2E_IDLE_CHECK_INTERVAL:=3s}"
: "${E2E_MIN_SCALE_DOWN_AGE:=30s}"
: "${E2E_SOAK_CYCLES:=6}"
: "${E2E_SCENARIO_SET:=mixed-traffic,dead-job-revival,idle-scaler-restart}"

: "${E2E_TRAFFIC_SHAPE:=warmup,rolling,storm}"
: "${E2E_TRAFFIC_SCENARIO:=storm}"
: "${E2E_K6_TARGET_MODE:=round-robin}"
: "${E2E_WARMUP_VUS:=5}"
: "${E2E_WARMUP_DURATION:=10s}"
: "${E2E_BURST_VUS:=50}"
: "${E2E_BURST_DURATION:=20s}"
: "${E2E_STORM_START_RATE:=25}"
: "${E2E_STORM_RATE:=250}"
: "${E2E_STORM_DURATION:=30s}"
: "${E2E_STORM_PREALLOCATED_VUS:=150}"
: "${E2E_STORM_MAX_VUS:=400}"

: "${E2E_GATE_TRAFFIC_SUCCESS_RATE:=0.995}"
: "${E2E_GATE_WAKE_P95_MS:=45000}"
: "${E2E_GATE_WAKE_P99_MS:=60000}"
: "${E2E_GATE_SCALE_TO_ZERO_MAX_SECONDS:=120}"
: "${E2E_GATE_DEPENDENCY_READY_MAX_SECONDS:=90}"

export E2E_PROFILE_DESCRIPTION \
  E2E_AUTOMATION_SMOKE_JOB \
  E2E_AUTOMATION_CERTIFICATION_JOB \
  E2E_AUTOMATION_JOB_NAME \
  E2E_TARGET_NOMAD_SERVERS \
  E2E_TARGET_NOMAD_CLIENTS \
  E2E_TARGET_CONSUL_SERVERS \
  E2E_TARGET_TRAEFIK_REPLICAS \
  E2E_TARGET_REDIS_NODES \
  E2E_TARGET_IDLE_SCALER_PLACEMENT \
  E2E_TARGET_IDLE_SCALER_ISOLATION_MODE \
  E2E_WORKLOAD_MIX_LABELS \
  E2E_WORKLOAD_FAST_API_COUNT \
  E2E_WORKLOAD_SLOW_START_COUNT \
  E2E_WORKLOAD_DEPENDENCY_SENSITIVE_COUNT \
  E2E_JOB_COUNT \
  E2E_NOMAD_CLIENTS \
  E2E_IDLE_TIMEOUT \
  E2E_IDLE_CHECK_INTERVAL \
  E2E_MIN_SCALE_DOWN_AGE \
  E2E_SOAK_CYCLES \
  E2E_SCENARIO_SET \
  E2E_TRAFFIC_SHAPE \
  E2E_TRAFFIC_SCENARIO \
  E2E_K6_TARGET_MODE \
  E2E_WARMUP_VUS \
  E2E_WARMUP_DURATION \
  E2E_BURST_VUS \
  E2E_BURST_DURATION \
  E2E_STORM_START_RATE \
  E2E_STORM_RATE \
  E2E_STORM_DURATION \
  E2E_STORM_PREALLOCATED_VUS \
  E2E_STORM_MAX_VUS \
  E2E_GATE_TRAFFIC_SUCCESS_RATE \
  E2E_GATE_WAKE_P95_MS \
  E2E_GATE_WAKE_P99_MS \
  E2E_GATE_SCALE_TO_ZERO_MAX_SECONDS \
  E2E_GATE_DEPENDENCY_READY_MAX_SECONDS
