# Copyright 2026 Metatable Inc.
# SPDX-License-Identifier: Apache-2.0

http:
  routers:
    s2z-fallback:
      rule: "HostRegexp(`^[a-z0-9-]+\\.localhost$`)"
      priority: 1
      entryPoints:
        - http
      service: s2z-activator

  services:
    s2z-activator:
      loadBalancer:
        passHostHeader: true
        healthCheck:
          path: /readyz
          interval: 5s
          timeout: 2s
        servers:
          - url: "http://activator:8090"
          - url: "http://activator-2:8090"
